.SUFFIXES: .cpp .c .o

OBJS = main.o timer_newer.o RemapperBase.o RemapperCell.o RemapperEdge.o NCFieldBase.o mpas_utils.o interp_utils.o

CXX = mpicxx -std=c++11 -mp -O3
CXXFLAGS = -I${NETCDF}/include
LDFLAGS = -L${NETCDF}/lib -lnetcdf -lnetcdff -lhdf5_hl -lhdf5 -lz -lpnetcdf

all: $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) $(LDFLAGS) -lrt

main.o: NCField.hpp

clean:
	rm -f a.out $(OBJS)

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

.c.o:
	$(CXX) $(CXXFLAGS) -c $<
