.SUFFIXES: .cpp .c .o

OBJS = main.o timer_newer.o RemapperBase.o RemapperCell.o RemapperEdge.o NCFieldBase.o mpas_utils.o interp_utils.o

CXX = CC -std=c++11 -fopenmp
CXXFLAGS = -I${NETCDF_DIR}/include
LDFLAGS = -L${NETCDF_DIR}/lib -lnetcdf -lnetcdff

all: $(OBJS)
	$(CXX) $(CXXFLAGS) $(OBJS) $(LDFLAGS) -lrt

main.o: NCField.hpp

clean:
	rm -f a.out $(OBJS)

.cpp.o:
	$(CXX) $(CXXFLAGS) -c $<

.c.o:
	$(CXX) $(CXXFLAGS) -c $<
